# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [29]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
#from google.colab import files
#uploaded = files.upload()
from sklearn.datasets import load_iris
df=load_iris()

In [0]:
import pandas as pd
import numpy as np

In [33]:
type(df)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X=df.data
Y=df.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=100)


In [36]:
X_train.shape

(112, 4)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
Y_train=to_categorical(Y_train,3)
Y_test=to_categorical(Y_test,3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model=tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
from tensorflow.keras.layers import Dense

In [0]:
model.add(Dense(4, activation='relu', input_shape=(4,)))
model.add(Dense(4, activation='relu'))
model.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy',
#model.compile(loss='binary_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [43]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 15        
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [44]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 1.4860 - accuracy: 0.3571 - val_loss: 1.4633 - val_accuracy: 0.2632
Epoch 2/100
112/112 [==============================] - 0s 221us/sample - loss: 1.3181 - accuracy: 0.3571 - val_loss: 1.3477 - val_accuracy: 0.2632
Epoch 3/100
112/112 [==============================] - 0s 223us/sample - loss: 1.2429 - accuracy: 0.3571 - val_loss: 1.2830 - val_accuracy: 0.2632
Epoch 4/100
112/112 [==============================] - 0s 248us/sample - loss: 1.1956 - accuracy: 0.3571 - val_loss: 1.2231 - val_accuracy: 0.2632
Epoch 5/100
112/112 [==============================] - 0s 233us/sample - loss: 1.1575 - accuracy: 0.3571 - val_loss: 1.1847 - val_accuracy: 0.2632
Epoch 6/100
112/112 [==============================] - 0s 168us/sample - loss: 1.1330 - accuracy: 0.3571 - val_loss: 1.1590 - val_accuracy: 0.2632
Epoch 7/100
112/112 [==============================] - 0s 187us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [45]:
model.predict(X_test[0:1])

array([[0.04311325, 0.35139015, 0.6054966 ]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [46]:
Y_test[0:1]

array([[0., 0., 1.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [48]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [50]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

Saving prices.csv to prices.csv


In [0]:
import pandas as pd
import numpy as np

df_price=pd.read_csv("prices.csv")

In [53]:
df_price.head()
#df_price.shape

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df_price=df_price.drop(['date','symbol'],axis=1)

In [55]:
df_price.shape

(851264, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [56]:
df_price=df_price[0:1000]
df_price.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X=df_price[["open", "close", "low", "high"]]
y=df_price['volume']
y=y/1000000

In [58]:
X.dtypes

open     float64
close    float64
low      float64
high     float64
dtype: object

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X=np.array(X)
Y=np.array(y)
X=X.astype("float32")
Y=Y.astype("float32")

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X=tf.math.l2_normalize(
    X,
    axis=None,
    epsilon=1e-12,
    name=None
)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
w=tf.zeros(shape=(4,1))
b=tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function 
def prediction(features,w,b):
  y_pred=tf.add(tf.matmul(features,w),b)
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual,y_predicted):
  diff=y_actual-y_predicted
  sqr=tf.square(diff)
  avg=tf.reduce_mean(sqr)
  return avg


## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X,y_actual,w,b,learning_rate=0.01):
  with tf.GradientTape() as t:
    t.watch([w,b])
    current_prediction=prediction(X,w,b)
    current_loss=loss(y_actual,current_prediction)

  dw,db=t.gradient(current_loss,[w,b])  

  w=w-learning_rate *dw
  b=b-learning_rate *db

  return w,b 

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [65]:
for i in range(100):
  W,b=train(X,Y,w,b)
  print('Current Training loss on iteration',i,loss(Y,prediction(X,w,b)).numpy())

Current Training loss on iteration 0 236.1682
Current Training loss on iteration 1 235.09424
Current Training loss on iteration 2 234.06282
Current Training loss on iteration 3 233.07217
Current Training loss on iteration 4 232.12048
Current Training loss on iteration 5 231.20685
Current Training loss on iteration 6 230.32932
Current Training loss on iteration 7 229.48653
Current Training loss on iteration 8 228.67712
Current Training loss on iteration 9 227.89975
Current Training loss on iteration 10 227.15286
Current Training loss on iteration 11 226.43588
Current Training loss on iteration 12 225.74736
Current Training loss on iteration 13 225.08597
Current Training loss on iteration 14 224.45088
Current Training loss on iteration 15 223.84048
Current Training loss on iteration 16 223.25485
Current Training loss on iteration 17 222.69215
Current Training loss on iteration 18 222.15169
Current Training loss on iteration 19 221.63264
Current Training loss on iteration 20 221.13428
Cur

### Observe values of Weight
- Print the updated values

In [66]:
print(w)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [67]:
print(b)

tf.Tensor([4.609452], shape=(1,), dtype=float32)
